version: "3"

services:
  with-docker-multi-env-staging:
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
    image: with-docker-multi-env-staging
    env_file:
      - ../../.env.staging # name of the env file
    ports:
      - "${APP_PORT}:3000"
