version: "3"

services:
  with-docker-multi-env-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: with-docker-multi-env-development
    env_file:
      - ../../.env.development # name of the env file
    ports:
      - "${APP_PORT}:3000"
