version: "3"

services:
  with-docker-multi-env-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: with-docker-multi-env-production
    env_file:
      - ../../.env.production # name of the env file
    ports:
      - "${APP_PORT}:3000"
